# This is a basic workflow to help you get started with Actions

name: pycheck

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 10 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "job1"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r ./requirements.txt
          pip3 list

      - name: Run python script
        run: |
          python3 ./pyscripts/pojie52.py
          python3 ./pyscripts/bilibili.py